const EXTENSION_EVENTS = Object.freeze({
  ACTIVATION_STARTED: "extension_activation_started",
  RUNTIME_INITIALIZING: "extension_runtime_initializing",
  RUNTIME_READY: "extension_runtime_ready",
  RUNTIME_DEGRADED: "extension_runtime_degraded",
  RUNTIME_FAILED: "extension_runtime_failed",
  WORKSPACE_ATTACHED: "extension_workspace_attached",
  WORKSPACE_DETACHED: "extension_workspace_detached",
  COMMAND_STARTED: "extension_command_started",
  COMMAND_COMPLETED: "extension_command_completed",
  COMMAND_FAILED: "extension_command_failed",
  VIEW_REFRESHED: "extension_view_refreshed",
  APPROVAL_PRESENTED: "extension_approval_presented",
  APPROVAL_RESOLVED: "extension_approval_resolved",
  OPERATION_CANCEL_REQUESTED: "extension_operation_cancel_requested",
  CONFIGURATION_CHANGED: "extension_configuration_changed",
  AGENT_EVENT: "extension_agent_event",
  PRODUCT_EXPERIENCE_EVENT: "extension_product_experience_event",
  PERSISTENCE_RESTORED: "extension_persistence_restored",
  PERSISTENCE_FAILED: "extension_persistence_failed",
  DEACTIVATION_STARTED: "extension_deactivation_started",
  DEACTIVATED: "extension_deactivated",
});

const EXTENSION_COMMANDS = Object.freeze([
  "levi.openDashboard",
  "levi.open",
  "levi.focusComposer",
  "levi.openBuildChat",
  "levi.openProjects",
  "levi.openSettings",
  "levi.newChat",
  "levi.showEnvironment",
  "levi.showActiveWorkflow",
  "levi.showActiveApproval",
  "levi.showActiveChange",
  "levi.initialize",
  "levi.openWorkspace",
  "levi.refreshWorkspace",
  "levi.analyzeProject",
  "levi.showProjectSummary",
  "levi.showArchitecture",
  "levi.showAssessment",
  "levi.showBlockers",
  "levi.showRisks",
  "levi.showNextActions",
  "levi.showReleaseReadiness",
  "levi.searchWorkspace",
  "levi.showCapabilities",
  "levi.showRuntimeHealth",
  "levi.showCertification",
  "levi.runCertification",
  "levi.showOperations",
  "levi.cancelOperation",
  "levi.showApprovals",
  "levi.respondToApproval",
  "levi.saveState",
  "levi.restoreState",
  "levi.understandCurrentFile",
  "levi.showModelProviders",
  "levi.showModels",
  "levi.showModelHealth",
  "levi.selectModel",
  "levi.testModelConnection",
  "levi.showModelUsage",
  "levi.configureProviderCredential",
  "levi.clearProviderCredential",
  "levi.openOnboarding",
  "levi.showContext",
  "levi.showTechnicalDetails",
  "levi.openAgent",
  "levi.newConversation",
  "levi.sendAgentMessage",
  "levi.cancelAgentTurn",
  "levi.retryAgentTurn",
  "levi.showAgentContext",
  "levi.showAgentPlan",
  "levi.showAgentTools",
  "levi.clearConversation",
  "levi.createChangeProposal",
  "levi.previewChange",
  "levi.previewFileDiff",
  "levi.validateChangeProposal",
  "levi.applyApprovedChange",
  "levi.rejectChange",
  "levi.revertChange",
  "levi.showChangeHistory",
  "levi.runChangeValidation",
  "levi.showValidationResult",
  "levi.showAllowedCommands",
  "levi.showSourceControlStatus",
  "levi.showSourceControlDiff",
  "levi.showMultiAgentTeam",
  "levi.previewDelegation",
  "levi.startDelegatedTask",
  "levi.cancelDelegatedTask",
  "levi.showAssignment",
  "levi.retryAssignment",
  "levi.requestAssignmentRevision",
  "levi.showAgentConflicts",
  "levi.resolveAgentConflict",
  "levi.reconcileAgentResults",
  "levi.showWorkflows",
  "levi.createWorkflow",
  "levi.startWorkflow",
  "levi.pauseWorkflow",
  "levi.resumeWorkflow",
  "levi.cancelWorkflow",
  "levi.retryWorkflow",
  "levi.showWorkflow",
  "levi.showWorkflowResult",
  "levi.showWorkflowSteps",
  "levi.retryWorkflowStep",
  "levi.skipWorkflowStep",
  "levi.showWorkflowCheckpoints",
  "levi.createWorkflowCheckpoint",
  "levi.restoreWorkflowCheckpoint",
  "levi.resolveWorkflowDecision",
  "levi.showPerformance",
  "levi.clearCache",
  "levi.runBenchmark",
  "levi.rebuildRepositoryGraph",
  "levi.showMemoryUsage",
  "levi.showReliability",
  "levi.runReliabilitySmoke",
  "levi.runReliabilityStandard",
  "levi.runReliabilityStrict",
  "levi.runReliabilityReleaseCandidate",
  "levi.cancelReliabilityRun",
  "levi.showReliabilityReport",
  "levi.showReliabilityBlockers",
  "levi.showReliabilityConsistency",
  "levi.showReliabilityRecovery",
  "levi.showReliabilityResources",
  "levi.showSecurityAssurance",
  "levi.runSecuritySmoke",
  "levi.runSecurityStandard",
  "levi.runSecurityStrict",
  "levi.runSecurityReleaseCandidate",
  "levi.cancelSecurityAudit",
  "levi.showSecurityReport",
  "levi.showSecurityBlockers",
  "levi.showSecurityFindings",
  "levi.showSecurityChecks",
  "levi.showThreatModel",
  "levi.showApprovalSecurity",
  "levi.showWorkspaceIsolation",
  "levi.showPromptInjectionReport",
  "levi.showSecretHandlingReport",
  "levi.showDependencySecurity",
  "levi.showSupplyChainSecurity",
  "levi.showStressScalability",
  "levi.runStressSmoke",
  "levi.runStressStandard",
  "levi.runStressStrict",
  "levi.runStressReleaseCandidate",
  "levi.cancelStressRun",
  "levi.showStressReport",
  "levi.showStressBlockers",
  "levi.showStressFindings",
  "levi.showStressRepositoryMetrics",
  "levi.showStressConcurrency",
  "levi.showStressMemory",
  "levi.showStressQueue",
  "levi.showStressProvider",
  "levi.showStressWorkflow",
  "levi.showStressCancellation",
  "levi.showStressPresentationPressure",
  "levi.showQualification",
  "levi.runQualificationSmoke",
  "levi.runQualificationStandard",
  "levi.runQualificationStrict",
  "levi.runQualificationReleaseCandidate",
  "levi.cancelQualificationRun",
  "levi.showQualificationReport",
  "levi.showQualificationBlockers",
  "levi.showQualificationManualChecks",
  "levi.showQualificationDefects",
  "levi.showQualificationFixtures",
  "levi.showQualificationJourneys",
  "levi.showExtensionHostQualification",
  "levi.showLocalOllamaQualification",
]);

const DEFAULT_WORKSPACE_EXCLUDES = Object.freeze([
  ".git/**",
  ".levi/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".cache/**",
  ".vscode-test/**",
  "vendor/**",
  "tmp/**",
  "temp/**",
  "**/*.min.js",
  "**/*.map",
]);

const UI_BOUNDS = Object.freeze({
  maximumTreeItemsPerSection: 50,
  maximumDisplayedOperations: 100,
  maximumDisplayedApprovals: 100,
  maximumDisplayedFindings: 50,
  maximumDisplayedEvidenceReferences: 20,
  maximumOutputMessageSize: 4000,
  maximumUiEventQueue: 200,
  maximumConcurrentViewRefreshes: 1,
  maximumWatcherCount: 8,
  maximumWorkspaceFiles: 500,
  maximumFileBytes: 262144,
  maximumSearchResults: 50,
  maximumVirtualDocumentSize: 200000,
  maximumAgentWebviewMessageSize: 64000,
  refreshThrottleMs: 100,
});

const TERMINAL_RUNTIME_EVENTS = Object.freeze([
  "runtime_ready",
  "runtime_degraded",
  "runtime_failed",
  "runtime_stopped",
  "workspace_ready",
  "workspace_degraded",
  "workspace_failed",
  "operation_succeeded",
  "operation_partially_succeeded",
  "operation_cancelled",
  "operation_failed",
  "operation_timed_out",
  "approval_requested",
  "approval_resolved",
  "approval_expired",
  "runtime_health_checked",
  "runtime_persisted",
  "runtime_restored",
  "runtime_corruption_detected",
  "workflow_created",
  "workflow_validated",
  "workflow_started",
  "workflow_paused",
  "workflow_resumed",
  "workflow_waiting_for_approval",
  "workflow_waiting_for_input",
  "workflow_step_ready",
  "workflow_step_started",
  "workflow_step_succeeded",
  "workflow_step_failed",
  "workflow_checkpoint_created",
  "workflow_recovery_started",
  "workflow_recovery_completed",
  "workflow_partially_completed",
  "workflow_completed",
  "workflow_cancelled",
  "workflow_failed",
  "performance_cache_cleared",
  "performance_invalidated",
  "performance_rebuild_completed",
  "performance_benchmark_completed",
  "performance_memory_budget_exceeded",
  "performance_corruption_detected",
  "reliability_ready",
  "reliability_degraded",
  "reliability_run_started",
  "reliability_run_progress",
  "reliability_run_cancelled",
  "reliability_run_completed",
  "reliability_run_partially_completed",
  "reliability_run_failed",
  "reliability_scenario_started",
  "reliability_scenario_succeeded",
  "reliability_scenario_failed",
  "reliability_release_blocker_detected",
  "reliability_certification_completed",
  "reliability_certification_blocked",
  "reliability_resource_leak_detected",
  "reliability_corruption_detected",
  "security_assurance_ready",
  "security_assurance_degraded",
  "security_audit_started",
  "security_audit_progress",
  "security_audit_cancelled",
  "security_audit_completed",
  "security_audit_partially_completed",
  "security_audit_failed",
  "security_scenario_started",
  "security_scenario_completed",
  "security_release_blocker_detected",
  "security_certification_completed",
  "security_certification_blocked",
  "stress_scalability_ready",
  "stress_scalability_degraded",
  "stress_run_started",
  "stress_run_progress",
  "stress_run_cancelled",
  "stress_run_completed",
  "stress_run_partially_completed",
  "stress_run_failed",
  "stress_scenario_started",
  "stress_scenario_completed",
  "stress_release_blocker_detected",
  "stress_certification_completed",
  "stress_certification_blocked",
  "qualification_ready",
  "qualification_degraded",
  "qualification_run_started",
  "qualification_run_progress",
  "qualification_run_waiting_for_manual",
  "qualification_run_cancelled",
  "qualification_run_completed",
  "qualification_run_partially_completed",
  "qualification_run_failed",
  "qualification_manual_check_failed",
  "qualification_release_blocker_detected",
  "qualification_certification_completed",
  "qualification_certification_blocked",
]);

module.exports = {
  DEFAULT_WORKSPACE_EXCLUDES,
  EXTENSION_COMMANDS,
  EXTENSION_EVENTS,
  TERMINAL_RUNTIME_EVENTS,
  UI_BOUNDS,
};
